Repository IBM/ibm-helm-api-operator, pull requests merged in 2020-08, with the labels that each got.

#60 integrate new CICD pipeline
  Makefile
  commonUtil/scripts/config_docker.sh
Labels: approved, lgtm, size/S

#61 40023 - downgrade manifest-tool to v0.7.0
  Makefile
Labels: approved, lgtm, size/XS

#62 remove quay credentials from manifest-tool
  Makefile
  README.md
Labels: approved, lgtm, size/XS

#64 removed productVersion annotation
  deploy/olm-catalog/ibm-helm-api-operator/3.6.2/ibm-helm-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
Labels: approved, lgtm, size/XS

#65 improve dev workflow
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/olm-catalog/ibm-helm-api-operator/3.6.2/ibm-helm-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/csv_images.sed
  helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/L

#66 remove force-upgrade annotation
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.2/ibm-helm-api-operator.v3.6.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#67 38013: ibm-helm-api-operator fails if rudder/tiller-secret exits
  Makefile
  helm-charts/helm-api/templates/helmapi-secret.yaml
  helm-charts/helm-api/templates/rudder-secret.yaml
  helm-charts/helm-api/templates/tiller-secret.yaml
Labels: approved, lgtm, size/M

#68 38759: increase memory for tiller
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.2/ibm-helm-api-operator.v3.6.2.clusterserviceversion.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/S

#69 fix audit image
  hack/csv_images.sed
Labels: approved

#70 40210: add pod anit-affinity for HA support
  Makefile
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
Labels: approved, lgtm, size/S

#71 removing secrets to allow operator upgrade
  deploy/olm-catalog/ibm-helm-api-operator/3.6.2/ibm-helm-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#72 40265 - update icp-audit-service image
  deploy/olm-catalog/ibm-helm-api-operator/3.6.2/ibm-helm-api-operator.v3.6.2.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/XS

#73 updated operator to v3.6.3
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-helm-api-operator/3.6.3/ibm-helm-api-operator.v3.6.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.3/operator.ibm.com_helmapis_crd.yaml
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
  helm-charts/helm-api/Chart.yaml
Labels: approved, lgtm, size/XL

#75 added multi-arch support labels
  deploy/olm-catalog/ibm-helm-api-operator/3.6.3/ibm-helm-api-operator.v3.6.3.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
