Repository IBM/ibm-helm-api-operator, pull requests merged in 2020-05, with the labels that each got.

#38 37259: changes to address restricted scc
  Makefile
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
  deploy/operator.yaml
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/helmapi-rbac.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
  helm-charts/helm-api/templates/tiller-rbac.yaml
Labels: approved, lgtm, size/M

#39 37644: revert crd back to v1alpha1
  .osdk-scorecard.yaml
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
  watches.yaml
Labels: approved, lgtm, size/S

#40 Readme and csv updates
  README.md
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#41 support operator upgrade from 3.3 to 3.4
  Makefile
  README.md
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
  deploy/operator.yaml
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/helmapi-rbac.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
  helm-charts/helm-api/values-metadata.yaml
  helm-charts/helm-api/values.yaml
  watches.yaml
Labels: approved, lgtm, size/L

#42 increase memory allocation to operator pod
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#43 37376: Update Helm foundation operators description and documentation
  README.md
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#44 37933: Helm foundation: Update productVersion metering annotations to…
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
Labels: approved, lgtm, size/XS

#46 remove unnecessary audit service setting
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
Labels: approved, lgtm, size/XS

#45 Cleanup2
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/L

#47 update instance labels to match operand
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, size/S

#48 labels pt2
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#49 37961: disable audit logging by default
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
  deploy/operator.yaml
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/values.yaml
  watches.yaml
Labels: approved, lgtm, size/M

#50 38052: Creating beta channel for cloud pak usage
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#51 add common scripts protect-csv and bump-up-csv
  .githooks/pre-commit
  Makefile
  commonUtil/scripts/bump-up-csv.sh
  commonUtil/scripts/protect-csv.sh
  commonUtil/scripts/push-csv.sh
Labels: approved, lgtm, size/L

#52 updated CSV from 3.6.0 to 3.6.1
  .osdk-scorecard.yaml
  Makefile
  deploy/olm-catalog/ibm-helm-api-operator/3.6.1/ibm-helm-api-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.1/operator.ibm.com_helmapis_crd.yaml
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
  deploy/operator.yaml
  helm-charts/helm-api/Chart.yaml
  helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/L

#53 update README.md
  README.md
Labels: approved, lgtm, size/XS

#54 changed icp-helm-api digest for new Z build
  deploy/olm-catalog/ibm-helm-api-operator/3.6.1/ibm-helm-api-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/S

#55 update icp-helm-api operand image
  deploy/olm-catalog/ibm-helm-api-operator/3.6.1/ibm-helm-api-operator.v3.6.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/S

#56 retrigger quay failed job
  OWNERS
Labels: approved, lgtm, size/XS

#57 38341: Helm Foundation - Move CS 3.4.1 into beta channel
  deploy/olm-catalog/ibm-helm-api-operator/3.6.1/ibm-helm-api-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
