Repository IBM/ibm-helm-api-operator, pull requests merged in 2020-04, with the labels that each got.

#22 fixed push-multi-arch target to push with git commit tag
  .gitignore
  Makefile
Labels: approved, lgtm, size/XS

#23 flesh out validation definitions
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
Labels: approved, lgtm, size/L

#24 3.5.0->3.6.0
  .osdk-scorecard.yaml
  Makefile
  README.md
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/L

#25 update 3.6.0 csv and crd
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
Labels: approved, lgtm, size/L

#26 make resource requests equal limits to avoid OOM
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/M

#27 update operator for blocking issue 37142
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/M

#28 audit service has new requirements
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/S

#29 36969: add operator dependencies
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#30 Update Chart.yaml version to 3.6.0
  helm-charts/helm-api/Chart.yaml
Labels: approved, lgtm, size/XS

#31 add dev channel
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
Labels: approved, lgtm, size/XS

#32 37228: remove unnecessarily exposed configurations
  .osdk-scorecard.yaml
  Makefile
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/crds/operator.ibm.com_v1_helmapi_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
  helm-charts/helm-api/values.yaml
  watches.yaml
Labels: approved, lgtm, size/XL

#33 fixes to prepare for integration build
  Makefile
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#34 Travis build troubleshooting
  Makefile
  README.md
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/crds/operator.ibm.com_v1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.5.0/operator.ibm.com_helmapis_crd.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  helm-charts/helm-api/Chart.yaml
  helm-charts/helm-api/LICENSES/LICENSE
  helm-charts/helm-api/README.md
  helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/helmapi-rbac.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
  helm-charts/helm-api/values-metadata.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/XL

#35 fix broken crd and csv
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
Labels: approved, lgtm, size/L

#36 37407: Remediate package vulnerability in ibmcom-amd64
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#37 use image digest instead of tags
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/crds/operator.ibm.com_v1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/ibm-helm-api-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.6.0/operator.ibm.com_helmapis_crd.yaml
  helm-charts/helm-api/ibm_cloud_pak/manifest.yaml
  helm-charts/helm-api/ibm_cloud_pak/qualification.yaml
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/L
