Repository IBM/ibm-helm-api-operator, pull requests merged in 2020-03, with the labels that each got.

#4 Refactor helm api operator
  .osdk-scorecard.yaml
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  commonUtil/resources/opencloud-operators.yaml
  commonUtil/scripts/generate-scorecard.sh
  commonUtil/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/0.0.1/ibm-helm-api-operator.v0.0.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/0.0.1/operator.ibm.com_helmapis_crd.yaml
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  helm-charts/helm-api/README.md
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/helmapi-rbac.yaml
  helm-charts/helm-api/templates/helmapi-secret.yaml
  helm-charts/helm-api/templates/rudder-secret.yaml
  helm-charts/helm-api/values.yaml
  watches.yaml
Labels: approved, lgtm, size/XL

#5 fix wrong package name, missing -app suffix
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
Labels: approved, lgtm, size/XS

#7 add tiller deployment
  Makefile
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/0.0.1/ibm-helm-api-operator.v0.0.1.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  helm-charts/helm-api/README.md
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/helmapi-secret.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
  helm-charts/helm-api/templates/tiller-rbac.yaml
  helm-charts/helm-api/templates/tiller-secret.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/L

#8 add healthcheck annotations for helm-api
  commonUtil/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/0.0.1/ibm-helm-api-operator.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
Labels: approved, lgtm, size/M

#9 fix rbac error when calling /api/v2/releases
  helm-charts/helm-api/templates/helmapi-rbac.yaml
Labels: approved, lgtm, size/M

#10 update csv version to 3.5.0
  .osdk-scorecard.yaml
  Makefile
  commonUtil/scripts/generate-scorecard.sh
  deploy/olm-catalog/ibm-helm-api-operator/3.5.0/ibm-helm-api-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.5.0/operator.ibm.com_helmapis_crd.yaml
Labels: approved, lgtm, size/L

#11 change current csv to 3.5.0
  deploy/olm-catalog/ibm-helm-api-operator/3.5.0/ibm-helm-api-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#12 add labels and license to docker files to pass image scan
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/M

#13 update healthcheck dependencies annotation
  helm-charts/helm-api/templates/deployment.yaml
Labels: approved, lgtm, size/XS

#14 add healthcheck dependency for tiller
  helm-charts/helm-api/templates/tiller-deploy.yaml
Labels: approved, lgtm, size/XS

#15 missing args in Dockerfile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.5.0/ibm-helm-api-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.5.0/operator.ibm.com_helmapis_crd.yaml
Labels: approved, lgtm, size/S

#16 fixes for addressing failure to install helm release
  Makefile
  helm-charts/helm-api/templates/helmapi-rbac.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
  helm-charts/helm-api/templates/tiller-secret.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/M

#18 clean up for RH certification
  Makefile
  deploy/crds/operator.ibm.com_helmapis_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.5.0/ibm-helm-api-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.5.0/operator.ibm.com_helmapis_crd.yaml
  deploy/olm-catalog/ibm-helm-api-operator/ibm-helm-api-operator.package.yaml
  deploy/operator.yaml
  helm-charts/helm-api/templates/deployment.yaml
  helm-charts/helm-api/templates/helmapi-rbac.yaml
  helm-charts/helm-api/templates/helmapi-secret.yaml
  helm-charts/helm-api/templates/ingress-liveness-probe.yaml
  helm-charts/helm-api/templates/ingress-readiness-probe.yaml
  helm-charts/helm-api/templates/ingress-swagger.yaml
  helm-charts/helm-api/templates/ingress-v1-rbac.yaml
  helm-charts/helm-api/templates/ingress-v2-rbac.yaml
  helm-charts/helm-api/templates/ingress-versions.yaml
  helm-charts/helm-api/templates/rudder-secret.yaml
  helm-charts/helm-api/templates/service.yaml
  helm-charts/helm-api/templates/tiller-deploy.yaml
  helm-charts/helm-api/templates/tiller-rbac.yaml
  helm-charts/helm-api/templates/tiller-secret.yaml
Labels: approved, lgtm, size/L

#19 missing annotations in CSV
  deploy/olm-catalog/ibm-helm-api-operator/3.5.0/ibm-helm-api-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#20 update icp-audit-service:3.3.1 to 3.4.0
  deploy/crds/operator.ibm.com_v1alpha1_helmapi_cr.yaml
  deploy/olm-catalog/ibm-helm-api-operator/3.5.0/ibm-helm-api-operator.v3.5.0.clusterserviceversion.yaml
  helm-charts/helm-api/values.yaml
Labels: approved, lgtm, size/XS

#21 add README.md
  README.md
  SECURITY_CONTACTS
Labels: approved, lgtm, size/M
